baseurl = "https://cunfus.github.io/hello-world/"
title = "你好，世界"
theme = "console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  # [[params.navlinks]]
  # name = "about/"
  # url = "about/"

  [[params.navlinks]]
  name = "消息"
  url = "news/"
  
  [[params.navlinks]]
  name = "专栏"
  url = "column/"
